
export {
  __velarStringSize as stringSize,
  __velarStringTrim as stringTrim,
  __velarStringUpper as stringUpper,
  __velarStringLower as stringLower,
  __velarStringSlice as stringSlice,
  __velarStringChar as stringChar,
  __velarStringHas as stringHas,
  __velarStringIndex as stringIndex,
  __velarStringCount as stringCount,
  __velarStringStartsWith as stringStartsWith,
  __velarStringEndsWith as stringEndsWith,
  __velarStringSplit as stringSplit,
  __velarStringReplace as stringReplace,
  __velarStringReplaceAll as stringReplaceAll,
  __velarStringPadStart as stringPadStart,
  __velarStringPadEnd as stringPadEnd,
  __velarStringRepeat as stringRepeat,
  __velarStringIsBlank as stringIsBlank,
  __velarStringCompare as stringCompare,
  __velarOrderCompare as orderCompare,
  __velarNumberAbs as numberAbs,
  __velarNumberRound as numberRound,
  __velarNumberFloor as numberFloor,
  __velarNumberCeil as numberCeil,
  __velarNumberSign as numberSign,
  __velarNumberTrunc as numberTrunc,
  __velarNumberToFixed as numberToFixed,
  __velarNumberIsInteger as numberIsInteger,
  __velarNumberIsSafeInteger as numberIsSafeInteger,
  __velarNumberIsNaN as numberIsNaN,
  __velarNumberIsFinite as numberIsFinite,
};
