import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { isContinuousIntegration, synchronizeRuntimeSources } from "../../scripts/build-packages.mjs";
import type { GeneratedRuntimeSources } from "../../scripts/generate-runtime-sources.mjs";

/**
 * D115 §一.4 / D114 — `scripts/build-packages.mjs` reconciles each package's
 * committed `runtime-sources.generated.ts` with the `runtime/**` it is a
 * transcription of.
 *
 * The defect this file pins reached the integration branch: the build rewrote
 * every transcription before anything else ran, so `check:runtime-sources`
 * compared the file the build had just written. A commit carrying a stale
 * transcription therefore went green locally *and* on CI — the gate was
 * structurally unable to see the thing it exists to see. Rewriting is right for
 * a person, who edited a runtime a moment ago; it is wrong for CI, whose job is
 * to judge the commit as it stands.
 */

/** A generated result for one package, over a real file on disk. */
async function fixture(text: string, committed: string | null): Promise<{ root: string; generated: string; result: GeneratedRuntimeSources }> {
  const root = await mkdtemp(join(tmpdir(), "velar-build-packages-"));
  const generated = join(root, "runtime-sources.generated.ts");
  if (committed !== null) await writeFile(generated, committed, "utf8");
  const result = {
    package: "core",
    manifest: { generated: "packages/core/src/runtime-sources.generated.ts" },
    base: join(root, "runtime"),
    generated,
    files: new Map([["list.js", "export const list = 1;\n"]]),
    values: new Map(),
    assemblies: new Map(),
    problems: [],
    text,
  } as unknown as GeneratedRuntimeSources;
  return { root, generated, result };
}

const FRESH = [
  "// Generated by scripts/generate-runtime-sources.mjs",
  "",
  "export const VELAR_CORE_LIST_SOURCE = \"the new body\";",
  "",
  "export const VELAR_CORE_TEST_SOURCE = \"unchanged\";",
  "",
].join("\n");

const STALE = FRESH.replace("the new body", "the old body");

test("a stale transcription is rewritten locally, and the notice says which file", async (context) => {
  const { root, generated, result } = await fixture(FRESH, STALE);
  context.after(() => rm(root, { recursive: true, force: true }));

  const notices = await synchronizeRuntimeSources(new Map([["core", result]]), { ci: false });
  assert.deepEqual(notices, ["regenerated packages/core/src/runtime-sources.generated.ts from 1 runtime sources"]);
  assert.equal(await readFile(generated, "utf8"), FRESH);

  // And a second pass has nothing to say, because nothing is stale.
  assert.deepEqual(await synchronizeRuntimeSources(new Map([["core", result]]), { ci: false }), []);
});

test("on CI a stale transcription is refused, naming the package, the constant and the remedy", async (context) => {
  const { root, generated, result } = await fixture(FRESH, STALE);
  context.after(() => rm(root, { recursive: true, force: true }));

  await assert.rejects(
    synchronizeRuntimeSources(new Map([["core", result]]), { ci: true }),
    (error: unknown) => {
      assert.ok(error instanceof Error);
      assert.match(error.message, /packages\/core: packages\/core\/src\/runtime-sources\.generated\.ts/u);
      // The line says where to look and the constant says what to look at.
      assert.match(error.message, /first differs at line 3, inside VELAR_CORE_LIST_SOURCE/u);
      assert.match(error.message, /node scripts\/generate-runtime-sources\.mjs/u);
      return true;
    },
  );
  // Refused means refused: the tree is left exactly as the commit left it, so
  // `check:runtime-sources` still has a stale file to find.
  assert.equal(await readFile(generated, "utf8"), STALE);
});

test("on CI a missing transcription is refused as missing rather than as a difference", async (context) => {
  const { root, result } = await fixture(FRESH, null);
  context.after(() => rm(root, { recursive: true, force: true }));

  await assert.rejects(
    synchronizeRuntimeSources(new Map([["core", result]]), { ci: true }),
    /packages\/core\/src\/runtime-sources\.generated\.ts is missing/u,
  );
});

test("a current transcription is left alone on both sides", async (context) => {
  const { root, generated, result } = await fixture(FRESH, FRESH);
  context.after(() => rm(root, { recursive: true, force: true }));

  assert.deepEqual(await synchronizeRuntimeSources(new Map([["core", result]]), { ci: true }), []);
  assert.deepEqual(await synchronizeRuntimeSources(new Map([["core", result]]), { ci: false }), []);
  assert.equal(await readFile(generated, "utf8"), FRESH);
});

test("a runtime source that disagrees with the constant it was resolved from stops the build either way", async (context) => {
  const { root, result } = await fixture(FRESH, FRESH);
  context.after(() => rm(root, { recursive: true, force: true }));
  const broken = { ...result, problems: ["runtime/list.js: does not contain the text VELAR_RUNTIME_REGISTRY_KEY renders"] } as GeneratedRuntimeSources;

  for (const ci of [true, false]) {
    await assert.rejects(
      synchronizeRuntimeSources(new Map([["core", broken]]), { ci }),
      /packages\/core: the runtime sources disagree with the constants they were resolved from/u,
      `ci=${ci}`,
    );
  }
});

test("CI is read from the environment the way the runners set it", () => {
  assert.equal(isContinuousIntegration({ CI: "true" }), true);
  assert.equal(isContinuousIntegration({ CI: "1" }), true);
  assert.equal(isContinuousIntegration({}), false);
  // A shell that exports one of the explicit falsehoods is a person's shell.
  for (const value of ["", "0", "false", "False"]) {
    assert.equal(isContinuousIntegration({ CI: value }), false, value);
  }
});
