import type { Span } from "./source.ts";

export type TokenKind =
  | "identifier"
  | "number"
  | "string"
  | "fstring"
  | "jsx"
  | "embeddedBlock"
  | "unitNumber"
  | "const"
  | "let"
  | "def"
  | "async"
  | "await"
  | "export"
  | "import"
  | "from"
  | "as"
  | "js"
  | "unsafe"
  | "extensionKeyword"
  | "extern"
  | "module"
  | "type"
  | "enum"
  | "abstract"
  | "class"
  | "extends"
  | "override"
  | "private"
  | "static"
  | "super"
  | "return"
  | "throw"
  | "assert"
  | "if"
  | "else"
  | "match"
  | "case"
  | "for"
  | "in"
  | "while"
  | "break"
  | "continue"
  | "try"
  | "catch"
  | "finally"
  | "pass"
  | "is"
  | "true"
  | "false"
  | "none"
  | "and"
  | "or"
  | "not"
  | "newline"
  | "indent"
  | "dedent"
  | "leftParen"
  | "rightParen"
  | "leftBracket"
  | "rightBracket"
  | "leftBrace"
  | "rightBrace"
  | "colon"
  | "comma"
  | "dot"
  | "ellipsis"
  | "question"
  | "optionalDot"
  | "nullish"
  | "arrow"
  | "fatArrow"
  | "pipe"
  | "assign"
  | "plusAssign"
  | "minusAssign"
  | "starAssign"
  | "slashAssign"
  | "percentAssign"
  | "equal"
  | "notEqual"
  | "less"
  | "lessEqual"
  | "greater"
  | "greaterEqual"
  | "plus"
  | "minus"
  | "star"
  | "starStar"
  | "slash"
  | "percent"
  | "eof";

export interface Token {
  readonly kind: TokenKind;
  readonly value: string;
  readonly span: Span;
}

export const keywordKinds: Readonly<Record<string, TokenKind>> = {
  const: "const",
  let: "let",
  def: "def",
  async: "async",
  await: "await",
  export: "export",
  import: "import",
  from: "from",
  as: "as",
  js: "js",
  unsafe: "unsafe",
  extern: "extern",
  module: "module",
  type: "type",
  enum: "enum",
  abstract: "abstract",
  class: "class",
  extends: "extends",
  override: "override",
  private: "private",
  static: "static",
  super: "super",
  return: "return",
  throw: "throw",
  assert: "assert",
  if: "if",
  else: "else",
  match: "match",
  case: "case",
  for: "for",
  in: "in",
  while: "while",
  break: "break",
  continue: "continue",
  try: "try",
  catch: "catch",
  finally: "finally",
  pass: "pass",
  is: "is",
  true: "true",
  false: "false",
  none: "none",
  and: "and",
  or: "or",
  not: "not",
};
