export const VELAR_NODE_WEBSOCKET_RUNTIME = String.raw`
import __VelarWebSocket, { WebSocketServer as __VelarWebSocketServer } from "ws";
import { createServer as __velarCreateHttpServer } from "node:http";
import { readFile as __velarServeReadFile, realpath as __velarServeRealpath, stat as __velarServeStat } from "node:fs/promises";
import { isAbsolute as __velarServeIsAbsolute, relative as __velarServeRelative, resolve as __velarServeResolve } from "node:path";
import { ServeRequest as __velarServeRuntime } from "velar/serve";

const __velarWebSocketConnections = new WeakMap();
const __velarWebSocketServers = new WeakMap();
const __velarServeNativeOperations = Object.freeze({readFile: __velarServeReadFile, realpath: __velarServeRealpath, stat: __velarServeStat, isAbsolute: __velarServeIsAbsolute, relative: __velarServeRelative, resolve: __velarServeResolve});
function __velarWsInteger(value, fallback, minimum, maximum, name) { if (value === undefined || value === null) return fallback; if (!Number.isSafeInteger(value) || value < minimum || value > maximum) throw new RangeError(name + " must be an integer from " + minimum + " through " + maximum); return value; }
function __velarWsDuration(value, fallback) { if (value === undefined || value === null) return fallback; if (typeof value !== "string") throw new TypeError("WebSocket timeout must be Duration"); const match = /^([+-]?(?:\d+(?:\.\d+)?|\.\d+))(ms|s)$/.exec(value); if (!match) throw new TypeError("WebSocket timeout must be Duration such as 5s"); const result = Number(match[1]) * (match[2] === "s" ? 1000 : 1); if (!Number.isFinite(result) || result < 0 || result > 2147483647) throw new RangeError("WebSocket timeout is outside the supported range"); return result; }
function __velarWsOptions(options = {}) { if (options === null || typeof options !== "object" || Array.isArray(options)) throw new TypeError("WebSocket options must be a record"); return { maxMessageBytes: __velarWsInteger(options.maxMessageBytes, 16 * 1024 * 1024, 1, 64 * 1024 * 1024, "maxMessageBytes"), maxQueuedMessages: __velarWsInteger(options.maxQueuedMessages, 256, 1, 10000, "maxQueuedMessages"), maxQueuedBytes: __velarWsInteger(options.maxQueuedBytes, 16 * 1024 * 1024, 1, 64 * 1024 * 1024, "maxQueuedBytes"), maxPendingSendBytes: __velarWsInteger(options.maxPendingSendBytes, 16 * 1024 * 1024, 1, 64 * 1024 * 1024, "maxPendingSendBytes") }; }
function __velarWsBytes(value) { if (value instanceof Uint8Array) { const output = new Uint8Array(value.byteLength); output.set(value); return output; } return null; }
function __velarWsMessageBytes(value) { if (typeof value === "string") return Buffer.byteLength(value, "utf8"); const bytes = __velarWsBytes(value); if (bytes) return bytes.byteLength; throw new TypeError("WebSocket.send requires text or Bytes"); }
export class WebSocketBackpressureError extends Error { constructor(message = "WebSocket backpressure limit exceeded") { super(message); this.name = "WebSocketBackpressureError"; } }
export class WebSocketClosedError extends Error { constructor(message = "WebSocket is closed") { super(message); this.name = "WebSocketClosedError"; } }
export class WebSocketProtocolError extends Error { constructor(message = "WebSocket protocol error") { super(message); this.name = "WebSocketProtocolError"; } }
export class WebSocketTimeoutError extends Error { constructor(message = "WebSocket timed out") { super(message); this.name = "WebSocketTimeoutError"; } }
function __velarWsFinish(state) { if (state.finished) return; state.finished = true; if (state.waiter) { const waiter = state.waiter; state.waiter = null; waiter.resolve(null); } }
function __velarWsAbort(state) { state.finished = true; state.queue.length = 0; state.queuedBytes = 0; if (state.waiter) { const waiter = state.waiter; state.waiter = null; waiter.resolve(null); } }
function __velarWsRejectReceive(state, socket, code, reason) { __velarWsAbort(state); socket.close(code, reason); }
function __velarWsWrap(socket, options) {
  const value = Object.create(__velarWsConnectionPrototype); const state = { socket, options, queue: [], queuedBytes: 0, waiter: null, pendingSendBytes: 0, finished: false, closePromise: null }; __velarWebSocketConnections.set(value, state);
  socket.binaryType = "arraybuffer";
  socket.on("message", (data, binary) => { if (state.finished) return; let message; let size; if (binary) { const source = data instanceof Uint8Array ? data : new Uint8Array(data); size = source.byteLength; if (size > options.maxMessageBytes) { __velarWsRejectReceive(state, socket, 1009, "Message too large"); return; } message = new Uint8Array(size); message.set(source); } else { message = typeof data === "string" ? data : data.toString("utf8"); size = Buffer.byteLength(message, "utf8"); if (size > options.maxMessageBytes) { __velarWsRejectReceive(state, socket, 1009, "Message too large"); return; } } if (state.waiter) { const waiter = state.waiter; state.waiter = null; waiter.resolve(message); } else if (state.queue.length >= options.maxQueuedMessages || state.queuedBytes + size > options.maxQueuedBytes) __velarWsRejectReceive(state, socket, 1009, "Unread message queue full"); else { state.queue.push(message); state.queuedBytes += size; } });
  socket.on("close", () => __velarWsFinish(state)); socket.on("error", error => { if (state.waiter) { const waiter = state.waiter; state.waiter = null; waiter.reject(new WebSocketProtocolError(error instanceof Error ? error.message : "WebSocket error")); } __velarWsAbort(state); });
  return Object.freeze(value);
}
const __velarWsConnectionPrototype = Object.freeze({
  state() { const state = __velarWebSocketConnections.get(this); if (!state) throw new TypeError("WebSocket state requires a connection"); return state.socket.readyState === __VelarWebSocket.CONNECTING ? "connecting" : state.socket.readyState === __VelarWebSocket.OPEN ? "open" : state.socket.readyState === __VelarWebSocket.CLOSING ? "closing" : "closed"; },
  send(message) { const state = __velarWebSocketConnections.get(this); if (!state) throw new TypeError("WebSocket.send requires a connection"); if (state.socket.readyState !== __VelarWebSocket.OPEN) return Promise.reject(new WebSocketClosedError()); const size = __velarWsMessageBytes(message); if (size > state.options.maxMessageBytes) return Promise.reject(new RangeError("WebSocket message exceeds maxMessageBytes")); if (state.pendingSendBytes + size > state.options.maxPendingSendBytes) return Promise.reject(new WebSocketBackpressureError()); const bytes = typeof message === "string" ? null : __velarWsBytes(message); state.pendingSendBytes += size; return new Promise((resolve, reject) => state.socket.send(bytes ?? message, { binary: bytes !== null }, error => { state.pendingSendBytes -= size; if (error) reject(new WebSocketClosedError(error.message)); else resolve(null); })); },
  next() { const state = __velarWebSocketConnections.get(this); if (!state) throw new TypeError("WebSocket.next requires a connection"); if (state.queue.length) { const message = state.queue.shift(); state.queuedBytes -= __velarWsMessageBytes(message); return Promise.resolve(message); } if (state.finished) return Promise.resolve(null); if (state.waiter) return Promise.reject(new WebSocketBackpressureError("Only one WebSocket.next call may wait at a time")); return new Promise((resolve, reject) => { state.waiter = { resolve, reject }; }); },
  close(code = 1000, reason = "") { const state = __velarWebSocketConnections.get(this); if (!state) throw new TypeError("WebSocket.close requires a connection"); if (!Number.isSafeInteger(code) || code < 1000 || code > 4999) return Promise.reject(new RangeError("WebSocket close code must be from 1000 through 4999")); if (typeof reason !== "string" || Buffer.byteLength(reason, "utf8") > 123) return Promise.reject(new RangeError("WebSocket close reason cannot exceed 123 UTF-8 bytes")); if (state.finished) return Promise.resolve(null); if (!state.closePromise) { state.closePromise = new Promise(resolve => state.socket.once("close", () => resolve(null))); state.socket.close(code, reason); } return state.closePromise; },
});
const __velarWsServerPrototype = Object.freeze({
  next() { const state = __velarWebSocketServers.get(this); if (!state) throw new TypeError("WebSocketServer.next requires a server"); if (state.queue.length) return Promise.resolve(state.queue.shift()); if (state.stopped) return Promise.resolve(null); if (state.waiter) return Promise.reject(new WebSocketBackpressureError("Only one WebSocketServer.next call may wait at a time")); return new Promise((resolve, reject) => { state.waiter = { resolve, reject }; }); },
  async stop() { const state = __velarWebSocketServers.get(this); if (!state) throw new TypeError("WebSocketServer.stop requires a server"); if (state.stopped) return null; state.stopped = true; if (state.waiter) { state.waiter.resolve(null); state.waiter = null; } for (const connection of state.connections) await connection.close(1001, "Server stopping"); await new Promise((resolve, reject) => state.server.close(error => error ? reject(error) : resolve(null))); if (state.httpServer) await new Promise((resolve, reject) => state.httpServer.close(error => error ? reject(error) : resolve(null))); return null; },
});
const __velarWsConnectionType = Object.freeze({ is(value) { return __velarWebSocketConnections.has(value); }, parse(value) { if (!this.is(value)) throw new TypeError("Value does not match WebSocketConnection"); return value; } });
const __velarWsServerType = Object.freeze({ is(value) { return __velarWebSocketServers.has(value); }, parse(value) { if (!this.is(value)) throw new TypeError("Value does not match WebSocketServer"); return value; } });
export const WebSocketConnection = __velarWsConnectionType; export const WebSocketServer = __velarWsServerType;
export function connect(url, options = {}) { if (typeof url !== "string" || !/^wss?:\/\//u.test(url)) return Promise.reject(new TypeError("WebSocket URL must start with ws:// or wss://")); const limits = __velarWsOptions(options); const timeout = __velarWsDuration(options.timeout, 10000); return new Promise((resolve, reject) => { const socket = new __VelarWebSocket(url, { maxPayload: limits.maxMessageBytes }); const timer = setTimeout(() => { socket.terminate(); reject(new WebSocketTimeoutError("WebSocket connection timed out")); }, timeout); socket.once("open", () => { clearTimeout(timer); resolve(__velarWsWrap(socket, limits)); }); socket.once("error", error => { clearTimeout(timer); reject(new WebSocketProtocolError(error instanceof Error ? error.message : "WebSocket connection failed")); }); }); }
export function listen(options) { if (options === null || typeof options !== "object" || Array.isArray(options)) return Promise.reject(new TypeError("listen requires an options record")); const limits = __velarWsOptions(options); const port = __velarWsInteger(options.port, 0, 0, 65535, "port"); const maxConnections = __velarWsInteger(options.maxConnections, 1024, 1, 100000, "maxConnections"); const maxPendingConnections = __velarWsInteger(options.maxPendingConnections, 128, 1, 10000, "maxPendingConnections"); if (options.host !== undefined && typeof options.host !== "string") return Promise.reject(new TypeError("WebSocket host must be text")); if (options.path !== undefined && (typeof options.path !== "string" || !options.path.startsWith("/"))) return Promise.reject(new TypeError("WebSocket path must start with '/'")); if (options.http !== undefined && typeof options.http !== "function") return Promise.reject(new TypeError("WebSocket http must be a velar/serve handler")); return new Promise((resolve, reject) => { const httpServer = options.http ? __velarCreateHttpServer((request, response) => { void __velarServeRuntime.__velarHandleNative(options.http, request, response, __velarServeNativeOperations); }) : null; const server = new __VelarWebSocketServer(httpServer ? { server: httpServer, path: options.path, maxPayload: limits.maxMessageBytes, perMessageDeflate: false, clientTracking: true } : { port, host: options.host ?? "127.0.0.1", path: options.path, maxPayload: limits.maxMessageBytes, perMessageDeflate: false, clientTracking: true }); const value = Object.create(__velarWsServerPrototype); const state = { server, httpServer, queue: [], waiter: null, stopped: false, connections: new Set() }; __velarWebSocketServers.set(value, state); server.on("connection", socket => { if (state.connections.size >= maxConnections || (!state.waiter && state.queue.length >= maxPendingConnections)) { socket.close(1013, "Server busy"); return; } const connection = __velarWsWrap(socket, limits); state.connections.add(connection); socket.once("close", () => state.connections.delete(connection)); if (state.waiter) { const waiter = state.waiter; state.waiter = null; waiter.resolve(connection); } else state.queue.push(connection); }); server.once("error", reject); const ready = () => { const address = (httpServer ?? server).address(); Object.defineProperty(value, "port", { value: typeof address === "object" && address ? address.port : port, enumerable: true }); resolve(Object.freeze(value)); }; if (httpServer) { httpServer.once("error", reject); httpServer.listen({port, host: options.host ?? "127.0.0.1"}, ready); } else server.once("listening", ready); }); }
`.trimStart();
